www/urls.py
#!/usr/bin/python
# coding: utf-8

# maposmatic, the web front-end of the MapOSMatic city map generation system
# Copyright (C) 2009  David Decotigny
# Copyright (C) 2009  Frédéric Lehobey
# Copyright (C) 2009  David Mentré
# Copyright (C) 2009  Maxime Petazzoni
# Copyright (C) 2009  Thomas Petazzoni
# Copyright (C) 2009  Gaël Utard

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import django
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

import maposmatic.feeds
import maposmatic.views
import settings

urlpatterns = patterns('',
    url(r'^$',
        maposmatic.views.index,
        name='main'),

    url(r'^new/$',
        maposmatic.views.new,
        name='new'),
    url(r'^recreate/$',
        maposmatic.views.recreate,
        name='recreate'),
    url(r'^cancel/$',
        maposmatic.views.cancel,
        name='cancel'),

    url(r'^maps/(?P<id>\d+)/(?P<nonce>[A-Za-z]{16})$',
        maposmatic.views.map_full,
        name='map-by-id-and-nonce'),
    url(r'^maps/(?P<id>\d+)$',
        maposmatic.views.map_full,
        name='map-by-id'),
    url(r'^maps/$',
        maposmatic.views.maps,
        name='maps'),

    url(r'^about/$',
        maposmatic.views.about,
        name='about'),
    url(r'^donate/$',
        maposmatic.views.donate,
        name='donate'),
    url(r'^donate-thanks/$',
        maposmatic.views.donate_thanks,
        name='donate-thanks'),

    (r'^apis/nominatim/$', maposmatic.views.api_nominatim),
    (r'^apis/reversegeo/([^/]*)/([^/]*)/$', maposmatic.views.api_nominatim_reverse),
    (r'^apis/papersize', maposmatic.views.api_papersize),
    (r'^apis/boundingbox/([^/]*)/$', maposmatic.views.api_bbox),

    # Feeds
    django.VERSION[1] >= 4 and \
        url(r'^feeds/maps/', maposmatic.feeds.MapsFeed(),
            name='rss-feed') or \
        url(r'^feeds/(?P<url>.*)/$',
            'django.contrib.syndication.views.feed',
            {'feed_dict': {'maps': maposmatic.feeds.MapsFeed}},
            name='rss-feed'),

    # Internationalization
    (r'^i18n/', include('django.conf.urls.i18n')),
)

if settings.DEBUG:
    urlpatterns.extend(patterns('',
        (r'^results/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.RENDERING_RESULT_PATH}),

        (r'^media/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.LOCAL_MEDIA_PATH}),
    ))

www/maposmatic/forms.py
# coding: utf-8

# maposmatic, the web front-end of the MapOSMatic city map generation system
# Copyright (C) 2009  David Decotigny
# Copyright (C) 2009  Frédéric Lehobey
# Copyright (C) 2009  Pierre Mauduit
# Copyright (C) 2009  David Mentré
# Copyright (C) 2009  Maxime Petazzoni
# Copyright (C) 2009  Thomas Petazzoni
# Copyright (C) 2009  Gaël Utard

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Forms for MapOSMatic

from django import forms
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _
import time

import ocitysmap
from www.maposmatic import models, widgets
import www.settings

class MapSearchForm(forms.Form):
    """
    The map search form, allowing search through the rendered maps.
    """

    query = forms.CharField(min_length=1, required=True,
                widget=forms.TextInput(attrs=
                    {'placeholder': _('Search for a map'),
                     'class': 'span2'}))

class MapRenderingJobForm(forms.ModelForm):
    """
    The main map rendering form, displayed on the 'Create Map' page. It's a
    ModelForm based on the MapRenderingJob model.
    """
    class Meta:
        model = models.MapRenderingJob
        fields = ('maptitle', 'administrative_city',
                  'lat_upper_left', 'lon_upper_left',
                  'lat_bottom_right', 'lon_bottom_right')

    MODES = (('admin', _('Administrative boundary')),
             ('bbox', _('Bounding box')))

    ORIENTATION = (('portrait', _('Portrait')),
                   ('landscape', _('Landscape')))

    mode = forms.ChoiceField(choices=MODES, initial='admin',
                             widget=forms.RadioSelect)
    layout = forms.ChoiceField(choices=(), widget=forms.RadioSelect)
    stylesheet = forms.ChoiceField(choices=(), widget=forms.RadioSelect)
    papersize = forms.ChoiceField(choices=(), widget=forms.RadioSelect)
    paperorientation = forms.ChoiceField(choices=ORIENTATION,
                                         widget=forms.RadioSelect)
    paper_width_mm = forms.IntegerField(widget=forms.HiddenInput)
    paper_height_mm = forms.IntegerField(widget=forms.HiddenInput)
    maptitle = forms.CharField(max_length=256, required=False)
    bbox = widgets.AreaField(label=_("Area"),
                             fields=(forms.FloatField(), forms.FloatField(),
                                     forms.FloatField(), forms.FloatField()))
    map_language = forms.ChoiceField(choices=www.settings.MAP_LANGUAGES_LIST,
                                     widget=forms.Select(
                                        attrs={'style': 'min-width: 200px'}))
    administrative_osmid = forms.IntegerField(widget=forms.HiddenInput,
                                              required=False)

    def __init__(self, *args, **kwargs):
        super(MapRenderingJobForm, self).__init__(*args, **kwargs)

        self._ocitysmap = ocitysmap.OCitySMap(www.settings.OCITYSMAP_CFG_PATH)

        layout_renderers = self._ocitysmap.get_all_renderers()
        stylesheets = self._ocitysmap.get_all_style_configurations()

        self.fields['layout'].choices = []
        for r in layout_renderers:
            if r.name == 'plain':
                description = _(u"Full-page layout without street index")
            elif r.name == 'single_page_index_side':
                description = _(u"Full-page layout with the street index on the side")
            elif r.name == 'single_page_index_bottom':
                description = _(u"Full-page layout with the street index at the bottom")
            elif r.name == 'multi_page':
                description = _(u"Multi-page layout")
            else:
                description = mark_safe(_(u"The %(layout_name)s layout") % {'layout_name':r.name})
            self.fields['layout'].choices.append((r.name, description))

        self.fields['layout'].initial = layout_renderers[0].name

        self.fields['stylesheet'].choices = []
        for s in stylesheets:
            if s.name == "Default":
                description = _("The default OpenStreetMap.org style")
            elif s.name == "MapQuestEu":
                description = _("The european MapQuest style")
            elif s.name == "MapQuestUs":
                description = _("The US MapQuest style")
            elif s.name == "MapQuestUk":
                description = _("The UK MapQuest style")
            elif s.name == "Printable":
                description = _("A MapOSMatic-specific stylesheet suitable for printing")
            else:
                description = mark_safe(_("The <i>%(stylesheet_name)s</i> stylesheet") % {'stylesheet_name':s.name})
            self.fields['stylesheet'].choices.append((s.name, description))

        self.fields['stylesheet'].initial = stylesheets[0].name

        def _build_papersize_description(p):
            if p[0] == "Best fit":
                return mark_safe(_("Best fit <em class=\"papersize\"></em>"))
            else:
                return mark_safe("%s <em class=\"papersize\">"
                                 "(%.1f &times; %.1f cm²)</em>"
                                 % (p[0], p[1] / 10., p[2] / 10.))

        self.fields['papersize'].choices = [
                (p[0], _build_papersize_description(p))
                for p in self._ocitysmap.get_all_paper_sizes()]

    def clean(self):
        """Cleanup function for the map query form. Different checks are
        required depending on the selected mode (by admininstrative city, or by
        bounding box).

        Returns the cleaned_data array.
        """

        cleaned_data = self.cleaned_data

        mode = cleaned_data.get("mode")
        city = cleaned_data.get("administrative_city")
        title = cleaned_data.get("maptitle")
        layout = cleaned_data.get("layout")
        stylesheet = cleaned_data.get("stylesheet")

        if cleaned_data.get("paperorientation") == 'landscape':
            cleaned_data["paper_width_mm"], cleaned_data["paper_height_mm"] = \
                cleaned_data.get("paper_height_mm"), cleaned_data.get("paper_width_mm")

        if title == '':
            msg = _(u"Map title required")
            self._errors["maptitle"] = forms.util.ErrorList([msg])
            del cleaned_data["maptitle"]

        if layout == '':
            msg = _(u"Layout required")
            self._errors["layout"] = forms.util.ErrorList([msg])
            del cleaned_data["layout"]

        if stylesheet == '':
            msg = _(u"Stylesheet required")
            self._errors["stylesheet"] = forms.util.ErrorList([msg])
            del cleaned_data["stylesheet"]

        if mode == 'admin':
            if city == "":
                msg = _(u"Administrative city required")
                self._errors["administrative_city"] = forms.util.ErrorList([msg])
                del cleaned_data["administrative_city"]

            # Make sure that bbox and admin modes are exclusive
            cleaned_data["lat_upper_left"] = None
            cleaned_data["lon_upper_left"] = None
            cleaned_data["lat_bottom_right"] = None
            cleaned_data["lon_bottom_right"] = None

            try:
                self._check_osm_id(cleaned_data.get("administrative_osmid"))
            except Exception,ex:
                msg = _(u"Error with osm city: %s" % ex)
                self._errors['administrative_osmid'] \
                    = forms.util.ErrorList([msg])

        elif mode == 'bbox':
            # Check bounding box corners are provided
            for f in [ "lat_upper_left", "lon_upper_left",
                       "lat_bottom_right", "lon_bottom_right" ]:
                val = cleaned_data.get(f)
                if val is None:
                    msg = _(u"Required")
                    self._errors['bbox'] = forms.util.ErrorList([msg])
                    if f in cleaned_data:
                        del cleaned_data[f]

            # Check latitude and longitude are different
            if (cleaned_data.get("lat_upper_left")
                == cleaned_data.get("lat_bottom_right")):
                msg = _(u"Same latitude")
                self._errors['bbox'] = forms.util.ErrorList([msg])
                del cleaned_data["lat_upper_left"]
                del cleaned_data["lat_bottom_right"]

            if (cleaned_data.get("lon_upper_left")
                == cleaned_data.get("lon_bottom_right")):
                msg = _(u"Same longitude")
                self._errors['bbox'] = forms.util.ErrorList([msg])
                del cleaned_data["lon_upper_left"]
                del cleaned_data["lon_bottom_right"]

            # Make sure that bbox and admin modes are exclusive
            cleaned_data["administrative_city"] = ''
            cleaned_data["administrative_osmid"] = None

            # Don't try to instanciate a bounding box with empty coordinates
            if self._errors:
                return cleaned_data

            lat_upper_left = cleaned_data.get("lat_upper_left")
            lon_upper_left = cleaned_data.get("lon_upper_left")
            lat_bottom_right = cleaned_data.get("lat_bottom_right")
            lon_bottom_right = cleaned_data.get("lon_bottom_right")

            boundingbox = ocitysmap.coords.BoundingBox(
                lat_upper_left, lon_upper_left,
                lat_bottom_right, lon_bottom_right)

www/templates/maposmatic/base.html
{% comment %}
 coding: utf-8

 maposmatic, the web front-end of the MapOSMatic city map generation system
 Copyright (C) 2009  David Decotigny
 Copyright (C) 2009  Frédéric Lehobey
 Copyright (C) 2009  David Mentré
 Copyright (C) 2009  Maxime Petazzoni
 Copyright (C) 2009  Thomas Petazzoni
 Copyright (C) 2009  Gaël Utard

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as
 published by the Free Software Foundation, either version 3 of the
 License, or any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}

{% load i18n %}
{% load extratags %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}"{% if LANGUAGE_BIDI %} dir="rtl"{% endif %}>
  <head>
    <title>MapOSMatic{% if DEBUG %} [DEV]{% endif %}: {% block title %}Welcome!{% endblock %}</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="shortcut icon" href="/media/img/favicon.png" />
    <link rel="stylesheet" href="/media/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/media/css/bootstrap-responsive.min.css" />
    <link rel="stylesheet" href="/media/css/maposmatic.css" />
    <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.4/leaflet.css" />
    <link rel="feed" title="{% trans "Maps feed" %}" href="/feed/maps/" />
  </head>

  <body class="{% block body-class %}{% endblock %}">
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>

          <div class="menu-status menu-status-{{ platform_status }} dropdown">
          <a rel="popover" class="brand popovered"
            data-animation="false"
            data-html="true"
            data-original-title="{% trans "Platform status" %}"
            data-placement="bottom"
            data-content='<p>{% trans "Rendering daemon: " %}<i class="pull-right icon-{% if daemon_running %}ok{% else %}off{% endif %}"></i></p>
            <p>{% trans "GIS database: " %}<i class="pull-right icon-{% if gis_lag_ok %}ok{% else %}{% if gis_lastupdate %}warning-sign{% else %}off{% endif %}{% endif %}"></i></p>'>
            <i class="icon-white icon-{{ platform_status }}"></i>
            MapOSMatic
          </a>
          </div>

          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="{% block menu-home   %}{% endblock %}"><a href="{% url main   %}"><i class="icon-white icon-home"></i> {% trans "Home" %}</a></li>
              <li class="{% block menu-new    %}{% endblock %}"><a href="{% url new    %}"><i class="icon-white icon-edit"></i> {% trans "Create map" %}</a></li>
              <li class="{% block menu-maps   %}{% endblock %}"><a href="{% url maps   %}"><i class="icon-white icon-list"></i> {% trans "Maps" %}</a></li>
              <li class="{% block menu-about  %}{% endblock %}"><a href="{% url about  %}"><i class="icon-white icon-comment"></i> {% trans "About" %}</a></li>
              <li class="{% block menu-donate %}{% endblock %}"><a href="{% url donate %}"><i class="icon-white icon-gift"></i> {% trans "Donate" %}</a></li>

              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="icon-white icon-flag"></i> {{ LANGUAGES|getitem:LANGUAGE_CODE }} <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <form action="/i18n/setlang/" method="post" name="langsel" class="navbar-form form-horizontal">
                  <input name="language" type="hidden" value="{{ LANGUAGE_CODE }}" />
                  {% for code, language in LANGUAGES.items %}
                  <li class="{% ifequal code LANGUAGE_CODE %}active{% endifequal %}">
                  <a href="javascript:(function() { document.langsel.language.value = '{{ code }}'; document.langsel.submit(); })();">{{ language }}</a>
                  </li>
                  {% endfor %}
                  </form>
                </ul>
              </li>

              <form action="{% url maps %}" method="get" class="navbar-form form-horizontal pull-right">
                <div class="control-group">
                  <div class="controls">
                    <div class="input-prepend">
                      <span class="add-on"><i class="icon-search"></i></span>
                      {{ searchform.query }}
                    </div>
                  </div>
                </div>
              </form>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="container" style="margin-top: 5em;">
      {% block page %}{% endblock %}
    </div>

    <footer class="footer">
      <p>
      {% blocktrans %}MapOSMatic is a free software webservice to generate maps of cities using OpenStreetMap data.{% endblocktrans %}
      </p>
      <p>
        <address><a href="mailto:contact@maposmatic.org">contact@maposmatic.org</a></address>
        &mdash;
        <code>irc://irc.freenode.net/#maposmatic</code>
      </p>
      <p class="hosted-by">
      {% blocktrans %}MapOSMatic website and rendering pipeline hosted by <a href="http://www.enix.org">eNiX</a>.<br />GIS database hosted by the <a href="http://www.fsffrance.org">Free Software Foundation France</a>.{% endblocktrans %}
      </p>
    </footer>

    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="http://openlayers.org/api/OpenLayers.js"></script>
    <script type="text/javascript" src="http://www.openstreetmap.org/openlayers/OpenStreetMap.js"></script>
    <script src="/media/js/bootstrap.min.js"></script>
    <script type="text/javascript">
      // Set focus to the search field
      $('#id_query').focus();

      $('.tooltipped').tooltip();
      $('.popovered').popover();

      var epsg_display_projection = new OpenLayers.Projection('EPSG:4326');
      var epsg_projection = new OpenLayers.Projection('EPSG:900913');

      function set_map_bounds(map, array, closest) {
        var bounds = new OpenLayers.Bounds();
        bounds.extend(new OpenLayers.LonLat(array[0][1], array[0][0]));
        bounds.extend(new OpenLayers.LonLat(array[1][1], array[1][0])); 
        bounds.transform(epsg_display_projection, epsg_projection);
        map.zoomToExtent(bounds, true);
      }

      function create_map(elt) {
        var map = new OpenLayers.Map(elt.attr('id'), {
          controls: [new OpenLayers.Control.Attribution()],
          maxExtent: new OpenLayers.Bounds(-20037508.34, - 20037508.34, 20037508.34, 20037508.34),
          numZoomLevels: 18,
          maxResolution: 156543.0399,
          projection: epsg_projection,
          displayProjection: epsg_display_projection
        });
        map.addLayer(new OpenLayers.Layer.OSM.Mapnik('Mapnik'));

        if (elt.attr('data-geo-osm-id') && elt.attr('data-geo-osm-id') != 'None') {
          $.getJSON('/apis/boundingbox/' + elt.attr('data-geo-osm-id') + '/',
            function(data) {
              set_map_bounds(map, data);
            })
            .error(function() {
              map.zoomToMaxExtent();
            });
        } else {
          set_map_bounds(map, [
            [elt.attr('data-geo-from-lat'), elt.attr('data-geo-from-lon')],
            [elt.attr('data-geo-to-lat'), elt.attr('data-geo-to-lon')]
          ]);
        }

        return map;
      }

      {% if gis_lastupdate %}
      $('.mapthumbnail').each(function(i, elt) {
        elt = $(elt);
        $('p', elt).hide();
        create_map(elt);
      });
      {% endif %}

      {% block extrajs %}{% endblock %}
    </script>

    <!-- Piwik statistics -->
    <script type="text/javascript">
      var pkBaseURL = (("https:" == document.location.protocol) ? "https://stats.maposmatic.org/piwik/" : "http://stats.maposmatic.org/piwik/");
      document.write(unescape("%3Cscript src='" + pkBaseURL
            + "piwik.js' type='text/javascript'%3E%3C/script%3E"));
    </script><script type="text/javascript">
      try {
        var piwikTracker = Piwik.getTracker(pkBaseURL + "piwik.php", {% if DEBUG %}3{% else %}2{% endif %});
        piwikTracker.trackPageView();
        piwikTracker.enableLinkTracking();
      } catch (err) {}
    </script>
    <noscript>
      <img src="http://stats.maposmatic.org/piwik/piwik.php?idsite={% if DEBUG %}3{% else %}2{% endif %}" />
    </noscript>
    <!-- End Piwik Tag -->
  </body>
</html>

www/templates/maposmatic/donate-thanks.html
{% extends "maposmatic/base.html" %}

{% comment %}
 coding: utf-8

 maposmatic, the web front-end of the MapOSMatic city map generation system
 Copyright (C) 2012  David Decotigny
 Copyright (C) 2012  Frédéric Lehobey
 Copyright (C) 2012  Pierre Mauduit
 Copyright (C) 2012  David Mentré
 Copyright (C) 2012  Maxime Petazzoni
 Copyright (C) 2012  Thomas Petazzoni
 Copyright (C) 2012  Gaël Utard

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as
 published by the Free Software Foundation, either version 3 of the
 License, or any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}
{% load i18n %}
{% load extratags %}

{% block body-class %}donate{% endblock %}
{% block menu-donate %}active{% endblock %}

{% block title %}{% trans "Thanks!" %}{% endblock %}
{% block page %}
<div class="hero-unit">
<h1>{% trans "Thanks for your donation!" %}</h1>

<p>
{% blocktrans %}<i class="icon-ok"></i> We have received your donation.
Thank you for your support to the MapOSMatic project!{% endblocktrans %}
</p>

<p class="info">
{% blocktrans %}You will receive a notification e-mail concerning your
donation. This e-mail will indicate that the donation has been received by
<i>Thomas Petazzoni</i>, who is the MapOSMatic developer in charge of donations
and funds. MapOSMatic is still an informal gathering of developers, and we have
not (yet) created a non-profit organization to support the project.{% endblocktrans %}
</p>
</div>
{% endblock %}

www/templates/maposmatic/donate.html
{% extends "maposmatic/base.html" %}

{% comment %}
 coding: utf-8

 maposmatic, the web front-end of the MapOSMatic city map generation system
 Copyright (C) 2012  David Decotigny
 Copyright (C) 2012  Frédéric Lehobey
 Copyright (C) 2012  Pierre Mauduit
 Copyright (C) 2012  David Mentré
 Copyright (C) 2012  Maxime Petazzoni
 Copyright (C) 2012  Thomas Petazzoni
 Copyright (C) 2012  Gaël Utard

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as
 published by the Free Software Foundation, either version 3 of the
 License, or any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}
{% load i18n %}
{% load extratags %}

{% block body-class %}donate{% endblock %}
{% block menu-donate %}active{% endblock %}

{% block title %}{% trans "Donate" %}{% endblock %}
{% block page %}
<h1>{% trans "Donate" %}</h1>
<h2>{% trans "Why are donations useful?" %}</h2>

{% url about as about_url %}

<p>
{% blocktrans %}MapOSMatic is a project entirely developed and maintained by a
team of volunteers (see our <a href="{{about_url}}">About</a> page for
details). However, running the MapOSMatic service and making improvements to it
has various costs beyond the time of the volunteer developers.{% endblocktrans %}
</p>

<p>
{% blocktrans %}Therefore, we are currently seeking donations to help us
funding:{% endblocktrans %}
</p>

<ul>
<li>{% blocktrans %}Participation to the transportation expenses of the
MapOSMatic developers when they gather for <i>hackfests</i> (meeting of
developers). You can read our <a href="http://news.maposmatic.org">blog</a> to
learn more about what we achieve during those hackfests. We usually implement a
huge number of improvements, new features and bug fixes during those meetings.
They take place during the holidays of the developers, and we would like to at
least compensate their travel expenses.{% endblocktrans %}</li>
</ul>

<h2>{% trans "Considering making a donation?" %}</h2>

<p>
{% blocktrans %}Donations can be done through the well-known <a
href="http://www.paypal.com">PayPal</a> service. We accept donations of any
amount: all donations are helpful, even the smallest ones.{% endblocktrans %}
</p>

<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
  <input type="hidden" name="cmd" value="_s-xclick" />
  <input type="hidden" name="hosted_button_id" value="YQPBAUM3JW8T2" />
  <input type="hidden" name="country" value="{{paypal_country_code}}" />
  <button type="submit" class="btn btn-large btn-primary" name="submit" alt="PayPal — The safer, easier way to pay online.">{% trans "Donate via PayPal &raquo;" %}</button>
  <img alt="" border="0" src="https://www.paypalobjects.com/{{paypal_lang_code}}/i/scr/pixel.gif" width="1" height="1"/>
</form>
{% endblock %}